const SELECTED_SLIDE_OUTLINE = 'solid 3px #0B57D0'
const SELECTED_OBJECT_OUTLINE = 'solid 2px #0B57D0'
const SELECTED_OBJECT_OUTLINE_SHADOW = '0px 0px 0px 1px #B9D2FB inset, 0px -2px 0px 1px #B9D2FB'

const MINIMUM_TEXT_SIZE = 1

const COLLECTION_SLIDE_SCALE = 1
const COLLECTION_SLIDE_OBJECT_SCALE = 0.19
const SELECTED_SLIDE_SCALE = 1

const SLIDE_COLLECTION_SCROLL_SPEED = 10
const SLIDE_COLLECTION_SCROLL_AREA = 30

const WORKSPACE_SLIDE_OBJECT_SCALE = 1

export {
    SELECTED_SLIDE_OUTLINE,
    SELECTED_OBJECT_OUTLINE,
    MINIMUM_TEXT_SIZE,
    COLLECTION_SLIDE_SCALE,
    SELECTED_SLIDE_SCALE,
    SLIDE_COLLECTION_SCROLL_SPEED,
    SLIDE_COLLECTION_SCROLL_AREA,
    COLLECTION_SLIDE_OBJECT_SCALE,
    WORKSPACE_SLIDE_OBJECT_SCALE,
    SELECTED_OBJECT_OUTLINE_SHADOW
}