const SELECTED_SLIDE_OUTLINE = 'solid 3.5px #6565FF'
const SELECTED_OBJECT_OUTLINE = 'solid 5px #6565FF'

const MINIMUM_TEXT_SIZE = 1

const COLLECTION_SLIDE_SCALE = 0.15
const SELECTED_SLIDE_SCALE = 1

export {
    SELECTED_SLIDE_OUTLINE,
    SELECTED_OBJECT_OUTLINE,
    MINIMUM_TEXT_SIZE,
    COLLECTION_SLIDE_SCALE,
    SELECTED_SLIDE_SCALE,
}